### ISSUE TITLE
Nord theme issue

### ISSUE THREAD

**Issue by dspasicpdy** [strayge/FmanAlternativeColors#5]
forest theme:
<img width="459" alt="fmannord2" src="https://user-images.githubusercontent.com/58466167/134654545-f4b99852-2ffe-4bfc-a62e-d01d407f9fd2.png">
nord theme:
<img width="422" alt="fmannord1" src="https://user-images.githubusercontent.com/58466167/134654557-c67cae19-6acb-4fe4-b602-e71f32ec80f9.png">
(only nord theme has boxes around dialogues)

How can i provide more informations?
(Mojave 10.14.6 mpbro)

Thanks

**Comment by strayge** [comment]
reason - very common rule:
```css
* {
    background: #434C5E;
}
```
probably fixed by [this](https://github.com/strayge/FmanAlternativeColors/commit/d612986b851bf5768838d5d5f16db7a27339859c) commit

can you update plugin and test it?

**Comment by dspasicpdy** [comment]
seems gone after reinstalling the plugin. 
sorry for stupid question: how does one upgrade plugin without reinstalling? 

Thanks for the quick response, i appreciate it! :)

**Comment by strayge** [comment]
only reinstall afaik
