### ISSUE TITLE
Shortcut to activate certain theme

### ISSUE THREAD

**Issue by albert-ying** [strayge/FmanAlternativeColors#6]
Thank you for this plugin. I'm wondering if there is a way I can set a shortcut for activating a specific theme? Say I want to activate Nord by doing `ctrl+n`

This will be helpful for integration with dynamic theme system provide by pywal

**Comment by strayge** [comment]
> I'm wondering if there is a way I can set a shortcut for activating a specific theme?

For now it can be set only via internal incremental id (each theme has some number, starting from 1).  
Order [depends ](https://stackoverflow.com/questions/6773584/how-is-pythons-glob-glob-ordered) on OS file listing, but it looks stable for me.

`C:\Users\<user>\AppData\Roaming\fman\Plugins\User\Settings\Key Bindings.json`
```json
[
    { "keys": ["Ctrl+N"], "command": "alternative_color_theme1" },
    { "keys": ["Ctrl+B"], "command": "alternative_color_theme2" }
]
```
![image](https://user-images.githubusercontent.com/2664578/152619136-2a35b97a-1be9-4059-b753-2a9e33f8f177.png)

Is it sufficient or need to set by name for create portable config?

**Comment by albert-ying** [comment]
It works for me! Thank you so much

**Comment by albert-ying** [comment]
Actually, I noticed that doing this doesn't re-read the theme file. As pressing the shortcut after changing the theme source file doesn't give me new theme.

**Comment by strayge** [comment]
quick test showed it works for me
![fman_change_colors1](https://user-images.githubusercontent.com/2664578/152728535-136ffe94-c427-4ef3-abfe-a6558f79ca5c.gif)
